apiVersion: v2
name: pinpoint
description: A Helm chart for Pinpoint
type: application
# chart version. 
version: 0.1.0
# version number of the application being deployed. 
appVersion: 2.5.0
# Dependency for Pinpoint
dependencies:
    - name: common
      version: 2.x.x
      repository: https://charts.bitnami.com/bitnami
    - name: mysql
      version: 1.6.7
      repository: https://charts.helm.sh/stable
      condition: mysql.enable
    - name: hdfs
      version: ~0.1.8
      repository: https://gradiant.github.io/bigdata-charts
      condition: hdfs.enabled
    - name: zookeeper
      version: ~2.1.0
      repository: https://charts.helm.sh/incubator
      condition: zookeeper.enabled
    - name: pinot
      version: ~0.2.6
      repository: https://raw.githubusercontent.com/apache/pinot/master/kubernetes/helm
      condition: pinot.enabled
    - name: kafka
      version: ~20.0.2
      repository: https://charts.bitnami.com/bitnami
      condition: kafka.enabled